### PR TITLE
UI: interactive offer

### PR DESCRIPTION
**Pull request by dckc**
fixes: #17 

## to try it out

Add `--dapp-branch dc-ui-tweaks` at the `yarn create` step:

```sh
yarn create @agoric/dapp --dapp-template dapp-offer-up --dapp-branch dc-ui-tweaks offer-up-tweaked
```

## initial state

 - [x] As a User, when the dapp loads up the page, it should show images of the 3 items / with images / and prices
 - [x] Update the Dapp with 3 images with the actual image of the item for sale
 - [x] Label them ("Items listed on OfferUp")

image

## with wallet connected

 - [x] Add 1 total price for all the items so its clear what is the offer I need to make
 - [x] As a User, I should be shown whats in my purse and what I own
 - [x] Rename to "Places I own" or "My Collectible items"
 - [x] Instead of "IST", label it "My Wallet (IST)"
 - [x] The button "Make Offer" -> change label to "Make an Offer"

image

## make offer

image

### CODE REVIEW

**Comment by kbennett2000** [comment]
That looks great! I love it - nice job!

**Review by kbennett2000 — APPROVED** [review]

**Comment by dckc** [comment]
## to try it out

Add `--dapp-branch dc-ui-tweaks` at the `yarn create` step:

```sh
yarn create @agoric/dapp --dapp-template dapp-offer-up --dapp-branch dc-ui-tweaks offer-up-tweaked
```

**Review by samsiegart — COMMENTED** [review]
LGTM, some non-blocking thoughts:

`yarn create` is sweet! But I think in the PR description you have two branches passed as arguments, typo? `--dapp-branch dc-ui-tweaks offer-up-tweaked`

It might be useful to have some input validation, it's not clear that you can only select 3 places and need 0.25 IST. Maybe just a message somewhere that says "Select at most 3 places and pay at least 0.25 IST" or something would work? I think allowing you to make the offer with invalid inputs is okay so people can see what happens with failed offers.

Visually, I wonder if it would look cleaner if we just removed all the table borders, and gave the buttons some minimal [styles](https://www.w3schools.com/css/tryit.asp?filename=trycss_buttons_round) (they just look like text right now)

Also, there's no issue linked here so I'm not sure what the intended scope of this work is. My main concern is that it's drifting further from a minimal example of hooking up `ui-kit` to a react app (maybe we can preserve that elsewhere?), but if Kris is aligned then I defer.

**Comment by dckc** [comment]
> there's no issue linked here so I'm not sure what the intended scope of this work is. 

oops! now there is: #17

> My main concern is that it's drifting further from a minimal example of hooking up `ui-kit` to a react app (maybe we can preserve that elsewhere?), but if Kris is aligned then I defer.

@sufyaankhan was the main advocate for a more visible offer UI. Yes, it's a balancing act. In due course we should write docs that explain every change we made to the react scaffold, and at that point, we might be able to organize it into files so that much of it is "just normal react code; nothing new here to explain" and the parts for watching vstorage and posting offers are emphasized. We'll want some ui-kits docs while we're at it.

> `yarn create` is sweet!

it sure is! ack: MFig, MH, and co.

> But I think in the PR description you have two branches passed as arguments, typo? `--dapp-branch dc-ui-tweaks offer-up-tweaked`

`offer-up-tweaked` was meant as the destination directory.

> It might be useful to have some input validation, it's not clear that you can only select 3 places and need 0.25 IST. Maybe just a message somewhere that says "Select at most 3 places and pay at least 0.25 IST" or something would work? I think allowing you to make the offer with invalid inputs is okay so people can see what happens with failed offers.

Especially since...

 - #21 

> Visually, I wonder if it would look cleaner if we just removed all the table borders, and gave the buttons some minimal [styles](https://www.w3schools.com/css/tryit.asp?filename=trycss_buttons_round) (they just look like text right now)

I can give that a try... if you have specific suggestions, I'm open to them.

**Comment by dckc** [comment]
## Input Validation

> It might be useful to have some input validation, it's not clear that you can only select 3 places and need 0.25 IST. Maybe just a message somewhere that says "Select at most 3 places and pay at least 0.25 IST" or something would work? I think allowing you to make the offer with invalid inputs is okay so people can see what happens with failed offers.

OK, I elaborated a couple labels and added error styling when the offer doesn't meet contract constraints:

image

**Comment by dckc** [comment]
## Button style

> Visually, I wonder if it would look cleaner if we just removed all the table borders, and gave the buttons some minimal [styles](https://www.w3schools.com/css/tryit.asp?filename=trycss_buttons_round) (they just look like text right now)

The button style suggestion seems straightforward:

image

### remove borders?

I tried removing the table borders; it doesn't separate the give and want as clearly, to me, so I left it alone, for now. I'm open to further input.

image

**Pull request merged**
